### ISSUE TITLE
Verify that usrp_driver will not start if the USRP fails to lock to an external reference or PPS

### ISSUE THREAD

**Issue by loxodes** [UAF-SuperDARN-OPS/SuperDARN_UHD_Server#40]

**Comment by loxodes** [comment]
Also, see what happens if the USRPs lose the reference clock after the driver is started.

**Comment by mguski** [comment]
It will not start without clock:
> Error: RuntimeError: Reference Clock PLL failed to lock to external source.

btw
Happend on USRP 43, we should check cables ...
