### ISSUE TITLE
xcf problem

### ISSUE THREAD

**Issue by wabristow** [UAF-SuperDARN-OPS/SuperDARN_UHD_Server#71]
The magnitude of the xcf data is about 50 dB lower than the acf data, which means the angle of arrival can't be calculated

**Comment by mguski** [comment]
looks like these amplitudes are better ...     

float   "acfd" [75][23][2]=
                66905.101562,   0.000000
                14699.210938,   -43830.789062
                62515.578125,   3535.105225
                84772.265625,   267.736847
                21200.000000,   5260.473633
....
        float   "xcfd" [75][23][2]=
                -9895.526367,   7227.157715
                -43339.421875,  7921.157715
                -4816.631348,   12107.052734
                -8842.262695,   20395.841797
                -14474.526367,  3826.421143
                -9022.262695,   20159.000000
                -12762.000000,  3876.947266
                -7791.473633,   21218.841797
                -13088.841797,  9692.262695
                -7438.842285,   6595.315918
                -13636.841797,  5047.000000
                -14290.210938,  8191.842285
                -8259.684570,   11872.473633
